Faceted browse UI v785th search results UI
nih-sparc/sparc-app pull request #304
Opened 2021-06-16 17:22 UTC by egauzens

# Description

Updated the dataset search results table view to match the wireframes for faceted browse, found here: https://app.abstract.com/share/ca9ac8ee-68b2-4422-b0d7-55a61c0bb403?collectionId=aac5183e-7ed8-469a-9d73-7e39036ce2ef&sha=deb221da2686562e2063344b84eaa2807aba5346

I tried to use an element ui table for displaying the list of properties but element ui makes it impossible to customize it how we wanted so I used an HTML table instead. 

I still have not updated the endpoint to point at algolia. That will be part of my next changeset. 

I created a constant array that maps what properties we want to display along with what the actual name of the property on the object is. I wasn't sure of a better way to do this. Feel free to suggest alternatives.

I left the sorting logic for the results table in, in case we want to keep sorting. However, it is still not accessible by the user bc the table header is now hidden 

## Type of change

- [ x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I ran the changes locally: Pull down the changes, 'run a yarn run dev', and then navigate to the Datasets tab

# Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests that prove my fix is effective or that my feature works

2021-06-16 18:06 UTC, Riccardo-Maio requested changes
Looks great, nice job on this! A few small changes that I suggested below and it will be good to go. Also, I would run eslint on this to fix any styling issues. We have defined rules in the `.eslintrc` file, so all you need to do is run `./node_modules/.bin/eslint --fix components/SearchResults/DatasetSearchResults.vue` and it should fix any styling issue for you automatically. I suggest running right before opening any PR so that we maintain consistent styling within our codebase.

2021-06-17 13:20 UTC, egauzens commented on components/SearchResults/DatasetSearchResults.vue
> +  font-weight: 500;
Agreed

2021-06-17 13:21 UTC, egauzens commented on components/SearchResults/DatasetSearchResults.vue
> +            </td>
Agreed

2021-06-18 12:42 UTC, Riccardo-Maio approved these changes
LGTM!

2021-06-18 14:59 UTC, merged