Tools and resources
nih-sparc/sparc-app pull request #357
Opened 2021-11-12 14:08 UTC by ignapas

# Description

Takes care of [this ticket](https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=676984160).

* Layouting for the new page, coming from [here](https://app.abstract.com/share/d7ffee59-e165-4809-a6c4-86c8cfc9c949?collectionLayerId=1afcd54d-36d3-4d5d-a6b0-926516897274&mode=design&sha=7bfba68b18f275d079c5e97f10c95556dd78fa64). Although some differences from the wireframe are kept for component reusability, a design review is very welcome.
* New content type created in Contentful for this layout. This page instance can be found [here](https://app.contentful.com/spaces/6bya4tyw8399/entries/1Yy2BEB0df8HxLNx2Ivsct).

**OTHER**
* Created new component Paper that is also used by the About page.

## Type of change

Delete those that don't apply.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests that prove my fix is effective or that my feature works

2021-11-13 14:37 UTC, egauzens commented on components/Chip/Chip.vue
> +<template>
Sorry I forgot to bring this up the other day, but there is already a component for this Called SparcPill. Could you remove this component and use that one instead? It looks to be identical. It looks like we are using it for the datasets results, I must have forgot to use it when making the about page refactor

2021-11-13 14:38 UTC, egauzens commented on components/Paper/Paper.vue
> +<style lang="scss" scoped>
Please move the css style definition below the script

2021-11-13 14:39 UTC, egauzens commented on components/Resources/FeaturedResource.vue
> +<style lang="scss" scoped>
Same here, please move the css style definition below the script

2021-11-13 14:42 UTC, egauzens requested changes
Nice work! Everything looks good, I like the creation of the Paper component. Just a couple minor things to address before submitting.

-Remove the Chip component and use SparcPill wherever the Chip is used
-move style definitions below script definition

2021-11-15 12:17 UTC, ignapas commented
> Nice work! Everything looks good, I like the creation of the Paper component. Just a couple minor things to address before submitting.
> 
> -Remove the Chip component and use SparcPill wherever the Chip is used -move style definitions below script definition

Got it, thanks for the review. I will make the changes asap.

2021-11-16 15:17 UTC, egauzens approved these changes
Lgtm! Thanks for making those changes

2021-11-17 14:23 UTC, merged