Dataset access and file citing
nih-sparc/sparc-app pull request #528
Opened 2022-09-14 15:16 UTC by ignapas

# Description

This PR tries to achieve the two following points

* Have access to the parent dataset from file metadata detail pages
* Be able to cite files from those pages

## Type of change

Delete those that don't apply.

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Manual test

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have utilized components from the Design System Library where applicable
- [ ] I have added unit tests that prove my fix is effective or that my feature works

2022-10-18 23:40 UTC, hsorby reviewed
There is way too much repeated content in this PR. The repeated content needs to be factored out into mixins, etc.

2022-10-28 14:13 UTC, egauzens requested changes
Why is there text that says 'TODO' for the cite section

2022-11-01 10:39 UTC, ignapas commented
> Why is there text that says 'TODO' for the cite section

I removed the TODOs

2022-11-02 20:09 UTC, egauzens approved these changes

2022-11-02 20:09 UTC, merged