Add alternative search when there are 0 results
nih-sparc/sparc-app pull request #637
Opened 2023-03-03 02:08 UTC by Tehsurfer

# Description

Return alternative search options to user when there are 0 search results
![image](https://user-images.githubusercontent.com/37255664/222613233-49ed5eb9-2962-4752-abcc-1846101a662f.png)

This new feature is requested in the wrike ticket:
https://www.wrike.com/open.htm?id=1014464589

This code can be checked at:
https://jesse-sprint-27.herokuapp.com/data?type=simulation&search=A%20New%20Paradigm

## Type of change

Delete those that don't apply.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Tested locally and others can test here:
https://jesse-sprint-27.herokuapp.com/data?type=simulation&search=A%20New%20Paradigm

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have utilized components from the Design System Library where applicable
- [ ] I have added unit tests that prove my fix is effective or that my feature works

2023-03-03 17:01 UTC, egauzens requested changes
there seems to be a bug with how it handles search results when it has found some and then you search again for something that should return 0 results, but it says there are still matches (eventhough the tab is not showing any). I am attaching a screen recording, because it is hard to verbalize. At the end of the video where I am circling the '4 results' with my mouse is what I am referring to. It should say no results. Also, I am not sure if this is what is intended, but no matter what tab you are on it says "No results found for DATASETS...instead of saying the name of the tab you are currently searching on

https://user-images.githubusercontent.com/5529126/222780816-f6d5ac78-79f3-458a-9d7f-145452215546.mp4

2023-03-05 07:09 UTC, Tehsurfer commented
Thanks @egauzens! Yeah I agree, I'll have a look at what's going on there on Monday

2023-03-07 02:05 UTC, Tehsurfer commented
@egauzens thanks for the feedback. Should be fixed now

2023-03-13 18:09 UTC, egauzens approved these changes

2023-03-13 18:10 UTC, merged