Send requests with S3 bucket name
nih-sparc/sparc-app pull request #643
Opened 2023-03-23 23:40 UTC by alan-wu

# Description

This update adds s3 bucket name into many of the requests. This update requires the changes from this sparc-api pull request to work - https://github.com/nih-sparc/sparc-api/pull/161

## Type of change

Delete those that don't apply.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I have tested this with old and new datasets and it can be tested here https://alan-wu-sparc-app.herokuapp.com/ .

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have utilized components from the Design System Library where applicable
- [ ] I have added unit tests that prove my fix is effective or that my feature works

2023-03-24 00:15 UTC, hsorby approved these changes
Looks good to me, I haven't crossed check against all the API that requires the s3Bucket correction.

2023-03-25 18:29 UTC, egauzens requested changes
Nice, I like the mixin for getting the dataset info. I think there is one file you missed though that has the path hardcoded:

mixins/request-download-file/index.js

2023-03-26 22:42 UTC, alan-wu commented
@

> Nice, I like the mixin for getting the dataset info. I think there is one file you missed though that has the path hardcoded:
> 
> mixins/request-download-file/index.js

@egauzens Thanks for catching that. It should now work with any bucket name. The easiest way to test is to go to the following two pages then view and download the changelog.
https://alan-wu-sparc-app.herokuapp.com/datasets/254?type=dataset&datasetDetailsTab=versions
https://alan-wu-sparc-app.herokuapp.com/datasets/307?type=dataset&datasetDetailsTab=versions

2023-03-26 23:12 UTC, egauzens approved these changes

2023-03-27 20:31 UTC, merged